version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      # 1. Mudamos para o entrypoint 'websecure' (HTTPS)
      - "traefik.http.routers.gnpcargo.entrypoints=websecure"
      - "traefik.http.routers.gnpcargo.rule=Host(`cargo.gnpsistemas.com.br`) && !PathPrefix(`/static/`)"
      - "traefik.http.routers.gnpcargo.tls=true"
      - "traefik.http.routers.gnpcargo.tls.certresolver=letsencrypt"
      # 2. Definimos uma prioridade para evitar conflito com a regra do static
      - "traefik.http.routers.gnpcargo.priority=10"
      - "traefik.http.services.gnpcargo.loadbalancer.server.port=8000"

    volumes:
      - static_volume:/app/staticfiles

  nginx-static:
    image: nginx:alpine
    volumes:
      - static_volume:/var/www/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      # 3. Nome único para o roteador de estáticos e HTTPS
      - "traefik.http.routers.gnpcargo-static.rule=Host(`cargo.gnpsistemas.com.br`) && PathPrefix(`/static/`)"
      - "traefik.http.routers.gnpcargo-static.entrypoints=websecure"
      - "traefik.http.routers.gnpcargo-static.tls=true"
      - "traefik.http.routers.gnpcargo-static.tls.certresolver=letsencrypt"
      # 4. Prioridade alta para garantir que o PathPrefix funcione antes da regra geral
      - "traefik.http.routers.gnpcargo-static.priority=100"
      - "traefik.http.services.gnpcargo-static.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true

volumes:
  static_volume:
