# Generated by Django 5.2.10 on 2026-01-20 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('cpfoucnpj', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_client', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('is_member_of_tenant', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=False, help_text='Allow access to the entity as system company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tenant', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['name'],
            },
        ),
    ]
