# Generated by Django 5.2.10 on 2026-01-21 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_rename_cpfoucnpj_entity_cpforcnpj_entityaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='is_supplier',
            new_name='is_shipping_company',
        ),
    ]
